---
meta:
  title: "Good idea: A VSCode plugin that highlights how often an error appears in Sentry, or other monitoring tools"
  description: I liberally throw errors defensively, often not expecting the error scenario to ever actually occur - it would be nice if I could see some real metrics about how often a thing is occurring, without having to leave the IDE. 
  dateCreated: 2023-10-09

series: 
  name: good_ideas
  part: 1
  description: Good ideas
---

I estimate that about 90% of the 'throw new Error' lines I write are for the purpose of type narrowing, and I usually don't expect them to occur. 

For example, say I have some code like this: 

```typescript
type User = {
    id?: string; 
    userName?: string; 
  }


  function usersPath(userId: string){
    return `/users/${userId}`
  }
  
  async function deleteUser(user: User) {
  
    //Argument of type 'string | undefined' is not assignable to parameter of type 'string'.
    //   Type 'undefined' is not assignable to type 'string'.ts(2345)
    fetch(usersPath(user.id), {
      method: "DELETE"
    })
  }
  
```

We have a simple type error, user.id could be undefined. 

For the sake of argument, let's assume that we're confident that this scenario isn't going to occur.

We have a few ways we might resolve this: 

- We could add a fallback value, a la usersPath(user.id ?? "default-id")` This doesn't make sense in this scenario - this would likely just cause a random 404 error at run time when it attempts to delete a user that doesn't exist. 
- We could add a `@ts-ignore`. At runtime we would `DELETE /users/undefined` - again giving us a random 404 error. 
- We could coerce the type a la `usersPath(user.id as string)` - but this would be the same as ignoring it - we would again get a random 404. 
- We can throw an error. 

```typescript 
  async function deleteUser(user: User) {
  
    if (!user.id){
      throw new Error("Encountered an user with no id.")
    }

    fetch(usersPath(user.id), {
      method: "DELETE"
    })
  }
```

Throwing an error creates a TypeScript [type guard](https://www.typescriptlang.org/docs/handbook/advanced-types.html#type-guards-and-differentiating-types), TypeScript is able to infer that the following the `throw` statement the type can no longer be undefined, and can thus treat it like a string. 

Encountering this error will be lot easier to debug than the error that will maybe result from our 404 error - now we're not going down a rabbit hole of investigating if there's something wrong with our API. 

But also remember, _we are not expecting that this scenario will actually happen_ the main reason we're throwing an error is just to appease TypeScript, and it's better to throw an error than to just ignore it. 

## What about tightening the contract? 

"Ah ha!" you say - "The real problem is that loosely typed `User` - we should make the id a required property. It's a code smell that it's optional". 

You might be right. But tightening the contract is easier said than than done. If we've got this type all through our codebase, making that type non-optional maybe no small feat. 

## But there's always a chance that the error is being thrown ðŸ¤”

In a large code base it's unclear what is really happening in the application. 

In the case that sometimes that that user ID doesn't exist, we might be giving the user a bad experience when we throw the error. 

If we're using a tool like Sentry we could have our [middleware](https://docs.sentry.io/platforms/javascript/guides/express/) reporting such errors. 

But the problem here is that's whole step removed from where we are, logging into sentry, searching for the particular error message is a bit of friction that a lot of developers aren't going to be bothered with. 

Instead, _it would be nice if we could see the prevalence of the errors in the IDE itself_. 

That is, we do something like this: 

```ts
  async function deleteUser(user: User) {
  
    if (!user.id){
      // PROD: 0 errors in last six months
      // TEST: 240 errors in last six months
      throw new SentryReportingError({
        type: "type-narrowing",
        message: "User ID did not exist"
      })
    }

    fetch(usersPath(user.id), {
      method: "DELETE"
    })
  }
```

Those comments are not comments at all, but annotations provided by the IDE via a plugin.
